version: '3'

services:
  php_test:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    ports:
      - '9000:9000'
    environment:
      - APP_ENV=test
      - APP_DEBUG=true
    entrypoint: >
      /bin/sh -c "php bin/phpunit"
